### ISSUE TITLE
Endpoint to get clusters available to particular user

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-cluster#15]
Currently we have endpoint which returns all the clusters available to OSIO. But we also need an endpoint to get user's clusters only (based on user access token).

```
GET /api/user/clusters
Authorization: Bearer {token}
```
 This endpoint will list clusters already configured and added to OSIO. There will be another endpoint (separate issue) to get all clusters available in UHC.

Tasks:
- [x] Add cluster and identity_cluster tables
- [x] Save cluster info in DB during startup and config map update https://github.com/fabric8-services/fabric8-cluster/issues/27
- [x] Design API in cluster - https://github.com/fabric8-services/fabric8-cluster/pull/33
- [x] Add api to create identity-cluster relationship for user registration flow #34
- [x] Changes required in auth https://github.com/fabric8-services/fabric8-auth/issues/720
